export const ApiUrl = {
  IMAGE_BASE_URL: "https://storage.googleapis.com/gymfreaky/",
  LOGIN_URL: `/auth/login`,
  REGISTER: `/auth/register`,
  AUTH_LOGOUT: `/auth/logout`,
  PLAN: `/plans`,
  STAFF: `/staff`,
  Member: `/members`,
  DASHBOARD: `/dashboard`,
  ROLES: `roles`,
  PAYMENTS: `payments`,
  DASHBOARD: `dashboard`,
  GYMS: `gyms`,
  MEDIA_URL: `media`,
  AUTH: `auth`,
};
